#SPDX-License-Identifier: M

---
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /mnt/demo2/index.html       #here we need to change file location.
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'

